import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Mystical SFX for the cinematic shuffle game. 16-bit PCM WAV assets
/// generated by `tools/generate_sounds.py`.
///
/// Singleton. Call [SoundService.instance.init] from `main()` once before
/// the first frame. After that, fire-and-forget [play] from any phase.
///
/// One [AudioPlayer] is held per sound; on replay we [seek] to zero and
/// [resume]. This keeps latency low (no asset loading on the hot path) and
/// also collapses rapid repeats into a single overlapping voice — useful
/// for `cardPick` when the seeker double-taps.
class SoundService {
  SoundService._();
  static final SoundService instance = SoundService._();

  static const _names = ['card_pick', 'shuffle', 'reveal', 'complete'];

  final Map<String, AudioPlayer> _pool = {};
  bool muted = false;
  double volume = 0.7;

  Future<void> init() async {
    for (final n in _names) {
      try {
        final p = AudioPlayer(playerId: 'juntra_$n');
        await p.setReleaseMode(ReleaseMode.stop);
        await p.setSource(AssetSource('sounds/$n.wav'));
        await p.setVolume(volume);
        _pool[n] = p;
      } catch (e) {
        // Audio backend may not be available (e.g. unit tests, headless CI,
        // or a desktop build without an audio plugin). Failing init quietly
        // keeps the rest of the app fully functional — `play()` then
        // simply no-ops because the key is absent.
        if (kDebugMode) debugPrint('SoundService init "$n" failed: $e');
      }
    }
  }

  Future<void> play(String name) async {
    if (muted) return;
    final p = _pool[name];
    if (p == null) return;
    try {
      await p.seek(Duration.zero);
      await p.resume();
    } catch (_) {
      // Swallow — sound is non-critical, never block the UI on it.
    }
  }

  /// Convenience accessors so callers don't sprinkle string keys around.
  Future<void> cardPick() => play('card_pick');
  Future<void> shuffle()  => play('shuffle');
  Future<void> reveal()   => play('reveal');
  Future<void> complete() => play('complete');

  Future<void> setVolume(double v) async {
    volume = v.clamp(0.0, 1.0);
    for (final p in _pool.values) {
      try { await p.setVolume(volume); } catch (_) {}
    }
  }

  Future<void> dispose() async {
    for (final p in _pool.values) {
      try { await p.dispose(); } catch (_) {}
    }
    _pool.clear();
  }
}
